export const SET_ALL_PROMOTIONS = 'SET_ALL_PROMOTIONS';
export const SET_FILTERED_PROMOTIONS = 'SET_FILTERED_PROMOTIONS';
export const SET_FILTER = 'SET_FILTER';
export const SET_PROMOCODE = 'SET_PROMOCODE';
export const CREATED_PROMOCODE = 'CREATED_PROMOCODE';